### ISSUE TITLE
Use TRAVIS_BUILD_ID when tagging the docker images

### ISSUE THREAD

**Issue by zelima** [datahq/deploy#134]
While service images are getting updated when something changes in the depended libraries, the deploy repo is not triggered since there are no changes detected to push to.

## Acceptance Criteria

* [ ] Modified images are updated in deploy repo as well. 

## Tasks

* [ ] Include when tagging images

 Example:

* When planner `repo` is updated -> 
* it triggers `specstore`. Its deploy script is triggered ->
* latest changes are pushed to the docker  ->
* and tagged under `TRAVIS_COMMIT` tag.
* script clones deploy repo ->
* tries to modify `values.yaml` ->
* But the image name and tag is the same ->
* skipps push back to the github

Since the TRAVIS_COMMIT remains the same as Git commit, when just triggering the build via Travis API, we are getting the same exact tag no matter what images are updated for the `spectore`.
 -> resulting in no changes in deploy repo. 

### Solution

As a solution think if we include TRAVIS_BUILD_ID together with TRAVIS_COMMIT we would have the new image every time the Travis is complete successfully.

```
tag="${TRAVIS_COMMIT}${TRAVIS_BUILD_ID}"
```

**Comment by akariv** [comment]
Good and simple solution :clap:
