### ISSUE TITLE
Use hosted elasticsearch on AWS

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#21]
* [x] Auto-deploy ES on AWS using boto (t2.micro) - http://boto3.readthedocs.io/en/latest/reference/services/es.html
  * [x] restrict by IP access using docker node ip address from previous step
     * [x] Prompt for docker node public ip address. You can this via `docker-cloud node inspect UUID-for-NODE` => json and public_ip address in there - for now we do this by hand (no need to automate)
  * [x] ~~restrict access with p/w and (maybe)~~ [p/w not possible] IP limiting ~~(that requires us to know the docker IP which creates a chicken and egg style problem so i'd suggest just going with p/w)~~
* [x] Add ES url to config ~~(including p/w + username)~~
  * [ ] ~~TODO: check whether this requires changes in metastore or assembler (does ES support "URI" style config or are the auth passed separately ...)~~ It does not require changes
* [x] Update docker-cloud to use this ES url
  * [x] delete ES service in docker cloud config
* [x] Deploy for production and testing
  * [x] delete ES service in docker cloud by hand

Extras

* [x] resize testing instance back to 2GB

Why? Avoid stuff like #20. Get kibana set up for free. Support auto-scaling. Roughly price equivalent for us.

**Comment by rufuspollock** [comment]
@zelima can you work on this as a priority on monday please.

**Comment by zelima** [comment]
FIXED
