### ISSUE TITLE
Separate assembler into another node

### ISSUE THREAD

**Issue by akariv** [datahq/deploy#34]
- [x] Create a new machine on datahub.io production
   - Same zone as the main machine (NY)
   - 4GB Memory
- [x] Tag the new machine as 'production-assembler'
- [x] Change the assembler deployment so that it has the tag 'production-assembler' instead of 'datahub-production'
- [x] Remove 'auto-redeploy' flag from assembler (in production)

Redeploy production and make sure that assembler container is on the new node (and only that).

/cc @zelima @rufuspollock @anuveyatsu

**Comment by zelima** [comment]
FIXED
