### ISSUE TITLE
Compare RDS pricing for postgres on AWS, Google and Azure

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#4]
Look at smallest and next smallest machine for continuous use (we don't need big RAM).

**Comment by zelima** [comment]
### AWS
Instance | Price
-- | --
db.t2.micro | $0.018
db.t2.small | $0.036

### Google
Instance | Price
-- | -- 
db-f1-micro | $0.0105
db-g1-small | $0.0350

**Comment by zelima** [comment]
FIXED see previous comment
