### ISSUE TITLE
Clarify configuration to get moving on local deployment

### ISSUE THREAD

**Issue by lwm** [datahq/deploy#46]
https://github.com/datahq/deploy#configuration

It is really not clear which values I need to have to run this locally.

Is this possible without an AWS/RDS account?

**Comment by lwm** [comment]
Something like https://github.com/datahq/frontend#env-vars, "When running locally ..." would be nice.

**Comment by zelima** [comment]
@lwm thanks for suggestion and I agree we should update README for frontend. 

Meanwhile, have you seen the environment variables here in `docker-compose.yaml` - you should be able to get all env variables from there https://github.com/datahq/deploy/blob/master/docker-compose.yml#L23

**Comment by lwm** [comment]
OK, I've setup a local elasticsearch and postgresql, configured those connection details and robbed anything else it complained about from the `docker-compose.yaml` and then ran `python main.py docker` and got:

```
(.venv) ➜  deploy (master) ✔ python main.py docker
Not authorized
Error:
No existing stack found. Creating ...
WARNING:dockercloudcli.interpolation:The DOCKERCLOUD_NODE_HOSTNAME variable is not set. Defaulting to a blank string.
Not authorized
Error:
```

I'll submit a PR to get some better error messages out of that.

**Comment by zelima** [comment]
@lwm Ok, this is our bad, the README is totally not clear about this, bit instructions in README.md is about setting up the on actual docker instance. You will need to have a docker node and `python main.py docker` will boot up all necessary, services there, ready to run. 

For local development, I would recommend using [DockerCompose.md](https://github.com/datahq/deploy/blob/master/DockerCompose.md), but not sure its documentation is up to date.

@lwm Can I get actual user stories behind this? What is the actual need? - so that I could help better

**Comment by lwm** [comment]
> @lwm Can I get actual user stories behind this? 

I pinged on the Gitter chat about Python hacking and @akariv sent me this way.  It sounded cool to be able to self-host datahub, so I thought I'd give it a bash. However, it does not appear to be a plug-and-play experience ;)

**Comment by zelima** [comment]
@lwm you can achieve that (boot up your own datahub locally) by using docker-compose. Just think it's documentation is a bit outdated (we introduced several new services recently). Let us update the documentation and will ping you here.

**Comment by zelima** [comment]
@lwm I updated DockerCompose. You should be able to setup everything locally. Please feel free to ask if anything goes wrong

**Comment by zelima** [comment]
Closing this as WONTFIX. Configurations in README are for live deployment. The same README now says that for the local setup you should take a look at DockerCompose.md
