### ISSUE TITLE
Deploy production service

### ISSUE THREAD

**Issue by rufuspollock** [datahq/deploy#6]
Domain is: **next.datahub.io** but set up everything else as if for datahub.io e.g. rawstore.datahub.io **not** rawstore-next.datahub.io

* [x] create your own .env.production and use that
  * [ ] Bonus: allow main.py to get a config option to specific the env file
* [x] deploy
  * [x] set tags on docker file to select node cluster:
    ```
     tags:
       - ${PROJECT}-${STAGE}
     ```
  * [x] Add note to README that node-cluster must exist with tag name `${PROJECT}-${STAGE}`
* [x] configure cloudflare

**Comment by zelima** [comment]
FIXED
